# Generated by Django 5.2.12 on 2026-03-30 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0001_initial'),
        ('pessoas', '0002_remove_pessoa_cpf_cnpj_remove_pessoa_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagar',
            old_name='vencimento',
            new_name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='pago',
        ),
        migrations.AddField(
            model_name='contapagar',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
