# Generated by Django 5.2.12 on 2026-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrecadacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_fechamento', models.DateField()),
            ],
        ),
    ]
