# Generated by Django 5.2.12 on 2026-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Morador', 'Morador'), ('Funcionario', 'Funcionário'), ('Fornecedor', 'Fornecedor')], max_length=20)),
            ],
        ),
    ]
