# Generated by Django 5.2.12 on 2026-03-19 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispensa', '0003_categoria_usuario_itemdispensa_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('mercado', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_avulso', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprado', models.BooleanField(default=False)),
                ('item_dispensa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispensa.itemdispensa')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.listacompra')),
            ],
        ),
    ]
