# Generated by Django 5.2.4 on 2026-03-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDispensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('KG', 'KG'), ('UNIDADE', 'UNIDADE'), ('PACOTE', 'PACOTE'), ('CAIXA', 'CAIXA'), ('LITRO', 'LITRO'), ('GRAMAS', 'GRAMAS')], max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispensa.categoria')),
            ],
        ),
    ]
