# Generated by Django 5.2.12 on 2026-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispensa',
            name='quantidade_ideal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
